# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codelens < Formula
  desc "Analyze JVM codebases (Java & Kotlin) — classes, methods, handlers, and more"
  homepage "https://github.com/charliek/codelens"
  version "0.0.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charliek/codelens/releases/download/v0.0.7/codelens_darwin_amd64.tar.gz"
      sha256 "68048e47400be5f5448a0d18aef3dc400d26976ee124e28b3f9aa22d4a23d302"

      define_method(:install) do
        bin.install "codelens"
        libexec.install "codelens-server-all.jar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charliek/codelens/releases/download/v0.0.7/codelens_darwin_arm64.tar.gz"
      sha256 "d58829f3bba8afd0288a4ccad6ffd344fee47913cea8ef6697f4795e21bcbc49"

      define_method(:install) do
        bin.install "codelens"
        libexec.install "codelens-server-all.jar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/codelens/releases/download/v0.0.7/codelens_linux_amd64.tar.gz"
      sha256 "93c6ec9d5b1d3d3a3fdd9c8530643111bac797379142fbfd7b35f2a0d42a653a"
      define_method(:install) do
        bin.install "codelens"
        libexec.install "codelens-server-all.jar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/codelens/releases/download/v0.0.7/codelens_linux_arm64.tar.gz"
      sha256 "e99f535df83271e678e2cb34e51b4cd1e659adc27032c70ff4c0164d1634341e"
      define_method(:install) do
        bin.install "codelens"
        libexec.install "codelens-server-all.jar"
      end
    end
  end

  def caveats
    <<~EOS
      codelens runs a JDK 21+ server under the hood. Provide a JDK via SDKMAN:
        sdk install java 21.0.9-amzn
      or Homebrew:
        brew install openjdk@21
      or point CODELENS_JAVA_HOME / JAVA_HOME at a JDK 21+ home.

      codelens auto-discovers JDKs from SDKMAN and Homebrew (openjdk@21..@25) and
      runs the server on the newest it finds. Analyzing a target project may also
      require that project's own JDK (likewise auto-discovered).

      Docs: https://charliek.github.io/codelens/
    EOS
  end

  test do
    system bin/"codelens", "version"
  end
end
