# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codelens < Formula
  desc "Analyze JVM codebases (Java & Kotlin) — classes, methods, handlers, and more"
  homepage "https://github.com/charliek/codelens"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charliek/codelens/releases/download/v0.0.1/codelens_darwin_amd64.tar.gz"
      sha256 "f086c594bf2c83283b973e8543bfd8b472bd048ad6b39e35e4e42778116f6f20"

      define_method(:install) do
        bin.install "codelens"
        libexec.install "codelens-server-all.jar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charliek/codelens/releases/download/v0.0.1/codelens_darwin_arm64.tar.gz"
      sha256 "bfb8ddd19126e5c1488b2b5810d865278e93080a3040222a3a861155f3e88b18"

      define_method(:install) do
        bin.install "codelens"
        libexec.install "codelens-server-all.jar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/codelens/releases/download/v0.0.1/codelens_linux_amd64.tar.gz"
      sha256 "a03180f92f807791c6b3cc2a9b441d4c9975ab28dd6db292768fc416abf25512"
      define_method(:install) do
        bin.install "codelens"
        libexec.install "codelens-server-all.jar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/codelens/releases/download/v0.0.1/codelens_linux_arm64.tar.gz"
      sha256 "640d205aa13e90b8bd82cfc1001c05ab1e1a9476ba2b8f15d0ed320ebf569d89"
      define_method(:install) do
        bin.install "codelens"
        libexec.install "codelens-server-all.jar"
      end
    end
  end

  def caveats
    <<~EOS
      codelens runs a JDK 21+ server under the hood. Provide a JDK via SDKMAN:
        sdk install java 21.0.9-amzn
      or Homebrew:
        brew install openjdk@21
      or point CODELENS_JAVA_HOME / JAVA_HOME at a JDK 21+ home.

      codelens auto-discovers JDKs from SDKMAN and Homebrew (openjdk@21..@25) and
      runs the server on the newest it finds. Analyzing a target project may also
      require that project's own JDK (likewise auto-discovered).

      Docs: https://charliek.github.io/codelens/
    EOS
  end

  test do
    system bin/"codelens", "version"
  end
end
