# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codelens < Formula
  desc "Analyze JVM codebases (Java & Kotlin) — classes, methods, handlers, and more"
  homepage "https://github.com/charliek/codelens"
  version "0.0.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charliek/codelens/releases/download/v0.0.4/codelens_darwin_amd64.tar.gz"
      sha256 "91736f6502f98d7d3a818452fbba8171a98389c9eff11963ddaf9a46bd10fb00"

      define_method(:install) do
        bin.install "codelens"
        libexec.install "codelens-server-all.jar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charliek/codelens/releases/download/v0.0.4/codelens_darwin_arm64.tar.gz"
      sha256 "51b5a0e9087973f680dcdaf1e66646ca2c7a571bfb833a053ca036ffa600d359"

      define_method(:install) do
        bin.install "codelens"
        libexec.install "codelens-server-all.jar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/codelens/releases/download/v0.0.4/codelens_linux_amd64.tar.gz"
      sha256 "cc743889cbdcc6f38c2edc837acdb63e16d47bc0a988674d8909a16ac9d0f9be"
      define_method(:install) do
        bin.install "codelens"
        libexec.install "codelens-server-all.jar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/codelens/releases/download/v0.0.4/codelens_linux_arm64.tar.gz"
      sha256 "48aa253fdc0ae04d6e64a641816adb3d406d70b0585856689d96ed77f027e91a"
      define_method(:install) do
        bin.install "codelens"
        libexec.install "codelens-server-all.jar"
      end
    end
  end

  def caveats
    <<~EOS
      codelens runs a JDK 21+ server under the hood. Provide a JDK via SDKMAN:
        sdk install java 21.0.9-amzn
      or Homebrew:
        brew install openjdk@21
      or point CODELENS_JAVA_HOME / JAVA_HOME at a JDK 21+ home.

      codelens auto-discovers JDKs from SDKMAN and Homebrew (openjdk@21..@25) and
      runs the server on the newest it finds. Analyzing a target project may also
      require that project's own JDK (likewise auto-discovered).

      Docs: https://charliek.github.io/codelens/
    EOS
  end

  test do
    system bin/"codelens", "version"
  end
end
