# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Craze < Formula
  desc "Terminal UI for coding agents: cursor-agent, grok, gx, or a built-in agent"
  homepage "https://github.com/charliek/craze"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charliek/craze/releases/download/v0.1.0/craze_darwin_amd64.tar.gz"
      sha256 "13732ac59dcad7f4d0595dd69fcf59492737345b092a7c24fc18f24cc4bb89b4"

      define_method(:install) do
        bin.install "craze"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charliek/craze/releases/download/v0.1.0/craze_darwin_arm64.tar.gz"
      sha256 "0ffd2c45fc75cdfca587fd95477f7330bc9a5f960dd7a88c9aebfda229234a6b"

      define_method(:install) do
        bin.install "craze"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/craze/releases/download/v0.1.0/craze_linux_amd64.tar.gz"
      sha256 "926954b32bd0fcc672f962813b61767a2615f49ae8e453e6c737826d7443f724"
      define_method(:install) do
        bin.install "craze"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/craze/releases/download/v0.1.0/craze_linux_arm64.tar.gz"
      sha256 "4bea888fcae1592f75552511b0144018584452dcd5e67254f11e3c9619a038d0"
      define_method(:install) do
        bin.install "craze"
      end
    end
  end

  def caveats
    <<~EOS
      craze's built-in agent needs no other CLI: `craze auth login` stores a
      model provider's API key, and `craze auth login chatgpt` signs in to a
      ChatGPT plan. cursor-agent, grok and gx are optional: install one and
      log in to drive it over ACP instead.
      Docs: https://charliek.github.io/craze/
    EOS
  end

  test do
    system bin/"craze", "version"
  end
end
