# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Craze < Formula
  desc "Terminal UI for Cursor and Grok coding agents over ACP"
  homepage "https://github.com/charliek/craze"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charliek/craze/releases/download/v0.0.1/craze_darwin_amd64.tar.gz"
      sha256 "90bb28cefa4621d0fe7bde5e57a6a73c56c5f739c0be17ddc764b50cb360bb7b"

      define_method(:install) do
        bin.install "craze"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charliek/craze/releases/download/v0.0.1/craze_darwin_arm64.tar.gz"
      sha256 "39dbbdb8a89a381bf8508992b3dc14781bfd9613600b403eabeb440127129da5"

      define_method(:install) do
        bin.install "craze"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/craze/releases/download/v0.0.1/craze_linux_amd64.tar.gz"
      sha256 "7d173d55f60140921efa7e0019543a29025bca39f700e9da8c2edf3dd60df97b"
      define_method(:install) do
        bin.install "craze"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/craze/releases/download/v0.0.1/craze_linux_arm64.tar.gz"
      sha256 "264bec1691d1bba81ad61ecc9de1b6af77a9db4cbd47cb9d4255686ecbb11803"
      define_method(:install) do
        bin.install "craze"
      end
    end
  end

  def caveats
    <<~EOS
      craze drives a coding agent that you install separately: the Cursor
      CLI (`cursor-agent login`) or the Grok CLI (`grok login`).
    EOS
  end

  test do
    system bin/"craze", "version"
  end
end
