# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envsecrets < Formula
  desc "CLI tool for managing encrypted environment files using GCS and age encryption"
  homepage "https://github.com/charliek/envsecrets"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charliek/envsecrets/releases/download/v0.0.8/envsecrets_darwin_amd64.tar.gz"
      sha256 "62d4761087b5d4807b86f7caaf7261273de738aae6424a8f83e309c7af6e9c3a"

      define_method(:install) do
        bin.install "envsecrets"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charliek/envsecrets/releases/download/v0.0.8/envsecrets_darwin_arm64.tar.gz"
      sha256 "7071710377a2763efe1d37ade7f8421dc6ebfbcd5126478f974de93df11d11d4"

      define_method(:install) do
        bin.install "envsecrets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/envsecrets/releases/download/v0.0.8/envsecrets_linux_amd64.tar.gz"
      sha256 "95f5455b6c4f00183f2c09e2e06e3d279a8893ebb26c03ad7cda2e46d7063c20"
      define_method(:install) do
        bin.install "envsecrets"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/envsecrets/releases/download/v0.0.8/envsecrets_linux_arm64.tar.gz"
      sha256 "d3e2c0d8c258933d5567dba70f656236a5887b39644c6d4f2248a59bf1d7bfc4"
      define_method(:install) do
        bin.install "envsecrets"
      end
    end
  end

  test do
    system bin/"envsecrets", "--version"
  end
end
