# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envsecrets < Formula
  desc "CLI tool for managing encrypted environment files using GCS and age encryption"
  homepage "https://github.com/charliek/envsecrets"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charliek/envsecrets/releases/download/v0.0.7/envsecrets_darwin_amd64.tar.gz"
      sha256 "f2e0152eda25ef87eb7705934032fd05af6a8308dcc3a8aa1ef3fa67efddd140"

      define_method(:install) do
        bin.install "envsecrets"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charliek/envsecrets/releases/download/v0.0.7/envsecrets_darwin_arm64.tar.gz"
      sha256 "487ab66ee2fad26d1c6753aae1a3a6b741940354d5c54704bdea7b22fd0e1964"

      define_method(:install) do
        bin.install "envsecrets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/envsecrets/releases/download/v0.0.7/envsecrets_linux_amd64.tar.gz"
      sha256 "4b88b61da7121348561e337a1e74dbf3799bfa218a7625ce86a5b452d81fd145"
      define_method(:install) do
        bin.install "envsecrets"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/envsecrets/releases/download/v0.0.7/envsecrets_linux_arm64.tar.gz"
      sha256 "b2fca3e04e1eaec53b54486e1c6f83fda7f79b5155f73a6291842c5d41da6c7b"
      define_method(:install) do
        bin.install "envsecrets"
      end
    end
  end

  test do
    system bin/"envsecrets", "--version"
  end
end
