# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prox < Formula
  desc "Modern process manager for development with API-first design"
  homepage "https://github.com/charliek/prox"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charliek/prox/releases/download/v0.2.3/prox_darwin_amd64.tar.gz"
      sha256 "1da701bddbb302308601bd291168da6a86d054a8a500bd7778d39cd3abc7e3dc"

      define_method(:install) do
        bin.install "prox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charliek/prox/releases/download/v0.2.3/prox_darwin_arm64.tar.gz"
      sha256 "daf2ea4931c4c18db0680be5c83dfe2e33251780ab9600d0facdff3c2d11867e"

      define_method(:install) do
        bin.install "prox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/prox/releases/download/v0.2.3/prox_linux_amd64.tar.gz"
      sha256 "e6c98fc6c30d263b55e79e5df22caa3a29f76823fcbce821ac48ff46a1930b54"
      define_method(:install) do
        bin.install "prox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/prox/releases/download/v0.2.3/prox_linux_arm64.tar.gz"
      sha256 "195d398a3ec61e6a49373f32748cd9104a56a461b516bd433ee000e5588b18d9"
      define_method(:install) do
        bin.install "prox"
      end
    end
  end

  test do
    system bin/"prox", "version"
  end
end
