# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prox < Formula
  desc "Modern process manager for development with API-first design"
  homepage "https://github.com/charliek/prox"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charliek/prox/releases/download/v0.2.2/prox_darwin_amd64.tar.gz"
      sha256 "0166cc46b419d063237e45f4cdcbb81989b76154477e39842eacdef8b166cbc8"

      define_method(:install) do
        bin.install "prox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charliek/prox/releases/download/v0.2.2/prox_darwin_arm64.tar.gz"
      sha256 "06ea858c6a56d05acb3d7ee8decc58e7d815d1f3f3a9a290959db4dc3cd23e7e"

      define_method(:install) do
        bin.install "prox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/prox/releases/download/v0.2.2/prox_linux_amd64.tar.gz"
      sha256 "c6e1eb8d55e63cd2ced28b861b7bb2124c148e1aed50b1c1aec15fb724044fab"
      define_method(:install) do
        bin.install "prox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/prox/releases/download/v0.2.2/prox_linux_arm64.tar.gz"
      sha256 "07db04e905d3523fc52e66c0f8edc6209ac355d85ca050ab75c5854d5901917b"
      define_method(:install) do
        bin.install "prox"
      end
    end
  end

  test do
    system bin/"prox", "version"
  end
end
