# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShedMachineRc < Formula
  desc "RC session helper for native machines (claude remote-control), sibling of shed-ext-rc"
  homepage "https://github.com/charliek/shed"
  version "0.7.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charliek/shed/releases/download/v0.7.9/shed-machine-rc_darwin_amd64.tar.gz"
      sha256 "9418d1671e63eb39ea72321cf7cd464ececdce1883bb54ab9c2b35e3787c027d"

      define_method(:install) do
        bin.install "shed-machine-rc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charliek/shed/releases/download/v0.7.9/shed-machine-rc_darwin_arm64.tar.gz"
      sha256 "fc9bf2068d89420399b8f60b5ebf1a62d45729f5263908a09cedf551918f5fe6"

      define_method(:install) do
        bin.install "shed-machine-rc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/shed/releases/download/v0.7.9/shed-machine-rc_linux_amd64.tar.gz"
      sha256 "c3e50d2b0419801c93dbbcf807a144cd1cb52e667b818a22ca303b2e92a31779"
      define_method(:install) do
        bin.install "shed-machine-rc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/shed/releases/download/v0.7.9/shed-machine-rc_linux_arm64.tar.gz"
      sha256 "a452e160d22402c0b0812c7f0af70247dea19a0de732f620a40f7e5276d9924f"
      define_method(:install) do
        bin.install "shed-machine-rc"
      end
    end
  end

  test do
    system bin/"shed-machine-rc", "version"
  end
end
