# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShedHostAgent < Formula
  desc "Host-side credential brokering agent for shed VMs"
  homepage "https://github.com/charliek/shed-extensions"
  version "0.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charliek/shed-extensions/releases/download/v0.4.3/shed-host-agent_darwin_amd64.tar.gz"
      sha256 "7679287ff1de6d5b85b61258f7be137f3c256fd0947870a40769880b8f22f3d6"

      define_method(:install) do
        bin.install "shed-host-agent"
        (etc/"shed").mkpath
        (etc/"shed").install "extensions.example.yaml" => "extensions.yaml" unless (etc/"shed/extensions.yaml").exist?
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charliek/shed-extensions/releases/download/v0.4.3/shed-host-agent_darwin_arm64.tar.gz"
      sha256 "23187bfbe3ed72b3c9c6ed65556f53ac1441f691215346bda14efe52a034520d"

      define_method(:install) do
        bin.install "shed-host-agent"
        (etc/"shed").mkpath
        (etc/"shed").install "extensions.example.yaml" => "extensions.yaml" unless (etc/"shed/extensions.yaml").exist?
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/shed-extensions/releases/download/v0.4.3/shed-host-agent_linux_amd64.tar.gz"
      sha256 "971ecab88e4e901bc8d0f34b3f0be2c4a0aa71ba4e3a82fff89ce2af796cb660"
      define_method(:install) do
        bin.install "shed-host-agent"
        (etc/"shed").mkpath
        (etc/"shed").install "extensions.example.yaml" => "extensions.yaml" unless (etc/"shed/extensions.yaml").exist?
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/shed-extensions/releases/download/v0.4.3/shed-host-agent_linux_arm64.tar.gz"
      sha256 "b57f590b0bd0d05b998b825fa7e6cbd4a725b0672abbd30cbb50aac3d697d802"
      define_method(:install) do
        bin.install "shed-host-agent"
        (etc/"shed").mkpath
        (etc/"shed").install "extensions.example.yaml" => "extensions.yaml" unless (etc/"shed/extensions.yaml").exist?
      end
    end
  end

  def caveats
    <<~EOS
      The shed-host-agent config has been installed to:
        #{HOMEBREW_PREFIX}/etc/shed/extensions.yaml

      Update that file with your shed server URL and any credential
      settings before starting the service.

      To start shed-host-agent as a background service:
        brew services start shed-host-agent

      Then verify it's running and see which config it loaded:
        shed-host-agent status

      Logs: #{var}/log/shed-host-agent.log
    EOS
  end

  service do
    # The agent writes its own size-capped, rotated operational log via
    # -log-file. launchd never rotates, so the previously-captured stderr log
    # grew unbounded (observed at 21 MB); error_log_path now only catches
    # pre-logger panics / runtime crashes (tiny).
    run [opt_bin/"shed-host-agent", "-config", etc/"shed/extensions.yaml", "-log-file", var/"log/shed-host-agent.log"]
    keep_alive true
    error_log_path var/"log/shed-host-agent.err.log"
    # launchd provides only a bare PATH; include the locations where Docker
    # Desktop (/usr/local/bin) and Homebrew (/opt/homebrew/bin) install
    # credential helpers so docker-credential-* can be resolved.
    environment_variables PATH: "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
  end

  test do
    system bin/"shed-host-agent", "version"
  end
end
