# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShedHostAgent < Formula
  desc "Host-side credential brokering agent for shed VMs"
  homepage "https://github.com/charliek/shed-extensions"
  version "0.3.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charliek/shed-extensions/releases/download/v0.3.7/shed-host-agent_darwin_amd64.tar.gz"
      sha256 "6911931192a9f4671ec07bd332f1563b223c3393005634fec8b046c3fd78b261"

      define_method(:install) do
        bin.install "shed-host-agent"
        (etc/"shed").mkpath
        (etc/"shed").install "extensions.example.yaml" => "extensions.yaml" unless (etc/"shed/extensions.yaml").exist?
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charliek/shed-extensions/releases/download/v0.3.7/shed-host-agent_darwin_arm64.tar.gz"
      sha256 "96f0aea22de190feaf956bd0f0dc5a0fe1d68b7b60b985b4a1a7ad19641a43a0"

      define_method(:install) do
        bin.install "shed-host-agent"
        (etc/"shed").mkpath
        (etc/"shed").install "extensions.example.yaml" => "extensions.yaml" unless (etc/"shed/extensions.yaml").exist?
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/shed-extensions/releases/download/v0.3.7/shed-host-agent_linux_amd64.tar.gz"
      sha256 "e7593f765ad4903bf11ad44280d2f10a0c706057a0c077fb1596628545479d4a"
      define_method(:install) do
        bin.install "shed-host-agent"
        (etc/"shed").mkpath
        (etc/"shed").install "extensions.example.yaml" => "extensions.yaml" unless (etc/"shed/extensions.yaml").exist?
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/shed-extensions/releases/download/v0.3.7/shed-host-agent_linux_arm64.tar.gz"
      sha256 "48820b894e5847e7302d934a878df12210f707f5f31c08ea311aafa11fa94f1b"
      define_method(:install) do
        bin.install "shed-host-agent"
        (etc/"shed").mkpath
        (etc/"shed").install "extensions.example.yaml" => "extensions.yaml" unless (etc/"shed/extensions.yaml").exist?
      end
    end
  end

  def caveats
    <<~EOS
      The shed-host-agent config has been installed to:
        #{HOMEBREW_PREFIX}/etc/shed/extensions.yaml

      Update that file with your shed server URL and any credential
      settings before starting the service.

      To start shed-host-agent as a background service:
        brew services start shed-host-agent

      Logs: #{var}/log/shed-host-agent.log
    EOS
  end

  service do
    # The agent writes its own size-capped, rotated operational log via
    # -log-file. launchd never rotates, so the previously-captured stderr log
    # grew unbounded (observed at 21 MB); error_log_path now only catches
    # pre-logger panics / runtime crashes (tiny).
    run [opt_bin/"shed-host-agent", "-config", etc/"shed/extensions.yaml", "-log-file", var/"log/shed-host-agent.log"]
    keep_alive true
    error_log_path var/"log/shed-host-agent.err.log"
    # launchd provides only a bare PATH; include the locations where Docker
    # Desktop (/usr/local/bin) and Homebrew (/opt/homebrew/bin) install
    # credential helpers so docker-credential-* can be resolved.
    environment_variables PATH: "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
  end

  test do
    system bin/"shed-host-agent", "version"
  end
end
