# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shed < Formula
  desc "CLI and server for managing persistent VM-based dev environments"
  homepage "https://github.com/charliek/shed"
  version "0.3.5"
  license "MIT"

  depends_on "vfkit" if OS.mac?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charliek/shed/releases/download/v0.3.5/shed-homebrew_darwin_amd64.tar.gz"
      sha256 "98a681cdbcd58b81105b482d7e1a05dd2e9659ce0891c112518986ca7868c48d"

      define_method(:install) do
        bin.install "shed"
        bin.install "shed-server"
        (etc/"shed").mkpath
        unless (etc/"shed/server.yaml").exist?
          if OS.mac?
            (etc/"shed/server.yaml").write <<~YAML
              # Shed Server Configuration
              # Full reference: https://github.com/charliek/shed/blob/main/configs/server.example.yaml

              name: my-server

              http_port: 8080
              ssh_port: 2222

              default_backend: vz
              log_level: info

              # Credentials to mount into VMs
              # Using ~/.shed/mounts/ keeps host and VM configs separate.
              # credentials:
              #   claude:
              #     source: ~/.shed/mounts/claude
              #     target: /home/shed/.claude
              #     readonly: false
              #   codex:
              #     source: ~/.shed/mounts/codex
              #     target: /home/shed/.codex
              #     readonly: false
              #   opencode_data:
              #     source: ~/.shed/mounts/opencode/share
              #     target: /home/shed/.local/share/opencode
              #     readonly: false
              #   opencode_state:
              #     source: ~/.shed/mounts/opencode/state
              #     target: /home/shed/.local/state/opencode
              #     readonly: false
              #   gh:
              #     source: ~/.shed/mounts/gh
              #     target: /home/shed/.config/gh
              #     readonly: false

              # Environment file (KEY=value per line, injected into VMs)
              # env_file: ~/.shed/env

              # Extensions provide credential brokering from host to VM.
              # Requires shed-host-agent to be installed and running:
              #   brew install shed-host-agent
              #   brew services start shed-host-agent
              # extensions:
              #   enabled:
              #     - ssh-agent
              #     - aws-credentials
              #     - docker-credentials

              vz:
                vfkit_path: vfkit
                kernel_path: ~/Library/Application Support/shed/vz/vmlinux
                initrd_path: ~/Library/Application Support/shed/vz/initrd.img
                base_rootfs: ghcr.io/charliek/shed-vz-experimental:v0.3.5
                images:
                  base: ghcr.io/charliek/shed-vz-base:v0.3.5
                  experimental: ghcr.io/charliek/shed-vz-experimental:v0.3.5
                instance_dir: ~/Library/Application Support/shed/vz/instances
                socket_dir: ~/.shed/vz/sockets
                default_cpus: 2
                default_memory_mb: 4096
                default_disk_gb: 20
                console_port: 1024
                notify_port: 1026
                tcp_proxy_port: 1028
                start_timeout: 60s
                stop_timeout: 10s
            YAML
          else
            (etc/"shed/server.yaml").write <<~YAML
              # Shed Server Configuration
              # Full reference: https://github.com/charliek/shed/blob/main/configs/server.example.yaml

              name: my-server

              http_port: 8080
              ssh_port: 2222

              default_backend: firecracker
              log_level: info

              # Credentials to mount into VMs
              # Using ~/.shed/mounts/ keeps host and VM configs separate.
              # credentials:
              #   claude:
              #     source: ~/.shed/mounts/claude
              #     target: /home/shed/.claude
              #     readonly: false
              #   codex:
              #     source: ~/.shed/mounts/codex
              #     target: /home/shed/.codex
              #     readonly: false
              #   gh:
              #     source: ~/.shed/mounts/gh
              #     target: /home/shed/.config/gh
              #     readonly: false

              # Environment file (KEY=value per line, injected into VMs)
              # env_file: ~/.shed/env

              # Extensions provide credential brokering from host to VM.
              # Requires shed-host-agent to be installed and running:
              #   brew install shed-host-agent
              #   brew services start shed-host-agent
              # extensions:
              #   enabled:
              #     - ssh-agent
              #     - aws-credentials
              #     - docker-credentials

              firecracker:
                kernel_path: /var/lib/shed/firecracker/images/vmlinux
                base_rootfs: ghcr.io/charliek/shed-fc-base:v0.3.5
                images:
                  base: ghcr.io/charliek/shed-fc-base:v0.3.5
                instance_dir: /var/lib/shed/firecracker/instances
                socket_dir: /var/run/shed/firecracker
                default_cpus: 2
                default_memory_mb: 4096
                default_disk_gb: 20
                vsock_base_cid: 100
                console_port: 1024
                notify_port: 1026
                start_timeout: 90s
                stop_timeout: 10s
                bridge_name: shed-br0
                bridge_cidr: 172.30.0.1/24
                tap_prefix: shed-tap
            YAML
          end
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charliek/shed/releases/download/v0.3.5/shed-homebrew_darwin_arm64.tar.gz"
      sha256 "741c6b33dbf66727cd3afeaefa76f71a713df337887724e56c1dbca5ed5403f4"

      define_method(:install) do
        bin.install "shed"
        bin.install "shed-server"
        (etc/"shed").mkpath
        unless (etc/"shed/server.yaml").exist?
          if OS.mac?
            (etc/"shed/server.yaml").write <<~YAML
              # Shed Server Configuration
              # Full reference: https://github.com/charliek/shed/blob/main/configs/server.example.yaml

              name: my-server

              http_port: 8080
              ssh_port: 2222

              default_backend: vz
              log_level: info

              # Credentials to mount into VMs
              # Using ~/.shed/mounts/ keeps host and VM configs separate.
              # credentials:
              #   claude:
              #     source: ~/.shed/mounts/claude
              #     target: /home/shed/.claude
              #     readonly: false
              #   codex:
              #     source: ~/.shed/mounts/codex
              #     target: /home/shed/.codex
              #     readonly: false
              #   opencode_data:
              #     source: ~/.shed/mounts/opencode/share
              #     target: /home/shed/.local/share/opencode
              #     readonly: false
              #   opencode_state:
              #     source: ~/.shed/mounts/opencode/state
              #     target: /home/shed/.local/state/opencode
              #     readonly: false
              #   gh:
              #     source: ~/.shed/mounts/gh
              #     target: /home/shed/.config/gh
              #     readonly: false

              # Environment file (KEY=value per line, injected into VMs)
              # env_file: ~/.shed/env

              # Extensions provide credential brokering from host to VM.
              # Requires shed-host-agent to be installed and running:
              #   brew install shed-host-agent
              #   brew services start shed-host-agent
              # extensions:
              #   enabled:
              #     - ssh-agent
              #     - aws-credentials
              #     - docker-credentials

              vz:
                vfkit_path: vfkit
                kernel_path: ~/Library/Application Support/shed/vz/vmlinux
                initrd_path: ~/Library/Application Support/shed/vz/initrd.img
                base_rootfs: ghcr.io/charliek/shed-vz-experimental:v0.3.5
                images:
                  base: ghcr.io/charliek/shed-vz-base:v0.3.5
                  experimental: ghcr.io/charliek/shed-vz-experimental:v0.3.5
                instance_dir: ~/Library/Application Support/shed/vz/instances
                socket_dir: ~/.shed/vz/sockets
                default_cpus: 2
                default_memory_mb: 4096
                default_disk_gb: 20
                console_port: 1024
                notify_port: 1026
                tcp_proxy_port: 1028
                start_timeout: 60s
                stop_timeout: 10s
            YAML
          else
            (etc/"shed/server.yaml").write <<~YAML
              # Shed Server Configuration
              # Full reference: https://github.com/charliek/shed/blob/main/configs/server.example.yaml

              name: my-server

              http_port: 8080
              ssh_port: 2222

              default_backend: firecracker
              log_level: info

              # Credentials to mount into VMs
              # Using ~/.shed/mounts/ keeps host and VM configs separate.
              # credentials:
              #   claude:
              #     source: ~/.shed/mounts/claude
              #     target: /home/shed/.claude
              #     readonly: false
              #   codex:
              #     source: ~/.shed/mounts/codex
              #     target: /home/shed/.codex
              #     readonly: false
              #   gh:
              #     source: ~/.shed/mounts/gh
              #     target: /home/shed/.config/gh
              #     readonly: false

              # Environment file (KEY=value per line, injected into VMs)
              # env_file: ~/.shed/env

              # Extensions provide credential brokering from host to VM.
              # Requires shed-host-agent to be installed and running:
              #   brew install shed-host-agent
              #   brew services start shed-host-agent
              # extensions:
              #   enabled:
              #     - ssh-agent
              #     - aws-credentials
              #     - docker-credentials

              firecracker:
                kernel_path: /var/lib/shed/firecracker/images/vmlinux
                base_rootfs: ghcr.io/charliek/shed-fc-base:v0.3.5
                images:
                  base: ghcr.io/charliek/shed-fc-base:v0.3.5
                instance_dir: /var/lib/shed/firecracker/instances
                socket_dir: /var/run/shed/firecracker
                default_cpus: 2
                default_memory_mb: 4096
                default_disk_gb: 20
                vsock_base_cid: 100
                console_port: 1024
                notify_port: 1026
                start_timeout: 90s
                stop_timeout: 10s
                bridge_name: shed-br0
                bridge_cidr: 172.30.0.1/24
                tap_prefix: shed-tap
            YAML
          end
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/shed/releases/download/v0.3.5/shed-homebrew_linux_amd64.tar.gz"
      sha256 "03c83a25ab47e8cddeb23d7bc62f372cf78fcc68e650357fea48c2cd6b9b5808"
      define_method(:install) do
        bin.install "shed"
        bin.install "shed-server"
        (etc/"shed").mkpath
        unless (etc/"shed/server.yaml").exist?
          if OS.mac?
            (etc/"shed/server.yaml").write <<~YAML
              # Shed Server Configuration
              # Full reference: https://github.com/charliek/shed/blob/main/configs/server.example.yaml

              name: my-server

              http_port: 8080
              ssh_port: 2222

              default_backend: vz
              log_level: info

              # Credentials to mount into VMs
              # Using ~/.shed/mounts/ keeps host and VM configs separate.
              # credentials:
              #   claude:
              #     source: ~/.shed/mounts/claude
              #     target: /home/shed/.claude
              #     readonly: false
              #   codex:
              #     source: ~/.shed/mounts/codex
              #     target: /home/shed/.codex
              #     readonly: false
              #   opencode_data:
              #     source: ~/.shed/mounts/opencode/share
              #     target: /home/shed/.local/share/opencode
              #     readonly: false
              #   opencode_state:
              #     source: ~/.shed/mounts/opencode/state
              #     target: /home/shed/.local/state/opencode
              #     readonly: false
              #   gh:
              #     source: ~/.shed/mounts/gh
              #     target: /home/shed/.config/gh
              #     readonly: false

              # Environment file (KEY=value per line, injected into VMs)
              # env_file: ~/.shed/env

              # Extensions provide credential brokering from host to VM.
              # Requires shed-host-agent to be installed and running:
              #   brew install shed-host-agent
              #   brew services start shed-host-agent
              # extensions:
              #   enabled:
              #     - ssh-agent
              #     - aws-credentials
              #     - docker-credentials

              vz:
                vfkit_path: vfkit
                kernel_path: ~/Library/Application Support/shed/vz/vmlinux
                initrd_path: ~/Library/Application Support/shed/vz/initrd.img
                base_rootfs: ghcr.io/charliek/shed-vz-experimental:v0.3.5
                images:
                  base: ghcr.io/charliek/shed-vz-base:v0.3.5
                  experimental: ghcr.io/charliek/shed-vz-experimental:v0.3.5
                instance_dir: ~/Library/Application Support/shed/vz/instances
                socket_dir: ~/.shed/vz/sockets
                default_cpus: 2
                default_memory_mb: 4096
                default_disk_gb: 20
                console_port: 1024
                notify_port: 1026
                tcp_proxy_port: 1028
                start_timeout: 60s
                stop_timeout: 10s
            YAML
          else
            (etc/"shed/server.yaml").write <<~YAML
              # Shed Server Configuration
              # Full reference: https://github.com/charliek/shed/blob/main/configs/server.example.yaml

              name: my-server

              http_port: 8080
              ssh_port: 2222

              default_backend: firecracker
              log_level: info

              # Credentials to mount into VMs
              # Using ~/.shed/mounts/ keeps host and VM configs separate.
              # credentials:
              #   claude:
              #     source: ~/.shed/mounts/claude
              #     target: /home/shed/.claude
              #     readonly: false
              #   codex:
              #     source: ~/.shed/mounts/codex
              #     target: /home/shed/.codex
              #     readonly: false
              #   gh:
              #     source: ~/.shed/mounts/gh
              #     target: /home/shed/.config/gh
              #     readonly: false

              # Environment file (KEY=value per line, injected into VMs)
              # env_file: ~/.shed/env

              # Extensions provide credential brokering from host to VM.
              # Requires shed-host-agent to be installed and running:
              #   brew install shed-host-agent
              #   brew services start shed-host-agent
              # extensions:
              #   enabled:
              #     - ssh-agent
              #     - aws-credentials
              #     - docker-credentials

              firecracker:
                kernel_path: /var/lib/shed/firecracker/images/vmlinux
                base_rootfs: ghcr.io/charliek/shed-fc-base:v0.3.5
                images:
                  base: ghcr.io/charliek/shed-fc-base:v0.3.5
                instance_dir: /var/lib/shed/firecracker/instances
                socket_dir: /var/run/shed/firecracker
                default_cpus: 2
                default_memory_mb: 4096
                default_disk_gb: 20
                vsock_base_cid: 100
                console_port: 1024
                notify_port: 1026
                start_timeout: 90s
                stop_timeout: 10s
                bridge_name: shed-br0
                bridge_cidr: 172.30.0.1/24
                tap_prefix: shed-tap
            YAML
          end
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/shed/releases/download/v0.3.5/shed-homebrew_linux_arm64.tar.gz"
      sha256 "4d12d67e8dcc6efba16341f330c7120d198d868d2dabf537d1fc3e5baed6eb48"
      define_method(:install) do
        bin.install "shed"
        bin.install "shed-server"
        (etc/"shed").mkpath
        unless (etc/"shed/server.yaml").exist?
          if OS.mac?
            (etc/"shed/server.yaml").write <<~YAML
              # Shed Server Configuration
              # Full reference: https://github.com/charliek/shed/blob/main/configs/server.example.yaml

              name: my-server

              http_port: 8080
              ssh_port: 2222

              default_backend: vz
              log_level: info

              # Credentials to mount into VMs
              # Using ~/.shed/mounts/ keeps host and VM configs separate.
              # credentials:
              #   claude:
              #     source: ~/.shed/mounts/claude
              #     target: /home/shed/.claude
              #     readonly: false
              #   codex:
              #     source: ~/.shed/mounts/codex
              #     target: /home/shed/.codex
              #     readonly: false
              #   opencode_data:
              #     source: ~/.shed/mounts/opencode/share
              #     target: /home/shed/.local/share/opencode
              #     readonly: false
              #   opencode_state:
              #     source: ~/.shed/mounts/opencode/state
              #     target: /home/shed/.local/state/opencode
              #     readonly: false
              #   gh:
              #     source: ~/.shed/mounts/gh
              #     target: /home/shed/.config/gh
              #     readonly: false

              # Environment file (KEY=value per line, injected into VMs)
              # env_file: ~/.shed/env

              # Extensions provide credential brokering from host to VM.
              # Requires shed-host-agent to be installed and running:
              #   brew install shed-host-agent
              #   brew services start shed-host-agent
              # extensions:
              #   enabled:
              #     - ssh-agent
              #     - aws-credentials
              #     - docker-credentials

              vz:
                vfkit_path: vfkit
                kernel_path: ~/Library/Application Support/shed/vz/vmlinux
                initrd_path: ~/Library/Application Support/shed/vz/initrd.img
                base_rootfs: ghcr.io/charliek/shed-vz-experimental:v0.3.5
                images:
                  base: ghcr.io/charliek/shed-vz-base:v0.3.5
                  experimental: ghcr.io/charliek/shed-vz-experimental:v0.3.5
                instance_dir: ~/Library/Application Support/shed/vz/instances
                socket_dir: ~/.shed/vz/sockets
                default_cpus: 2
                default_memory_mb: 4096
                default_disk_gb: 20
                console_port: 1024
                notify_port: 1026
                tcp_proxy_port: 1028
                start_timeout: 60s
                stop_timeout: 10s
            YAML
          else
            (etc/"shed/server.yaml").write <<~YAML
              # Shed Server Configuration
              # Full reference: https://github.com/charliek/shed/blob/main/configs/server.example.yaml

              name: my-server

              http_port: 8080
              ssh_port: 2222

              default_backend: firecracker
              log_level: info

              # Credentials to mount into VMs
              # Using ~/.shed/mounts/ keeps host and VM configs separate.
              # credentials:
              #   claude:
              #     source: ~/.shed/mounts/claude
              #     target: /home/shed/.claude
              #     readonly: false
              #   codex:
              #     source: ~/.shed/mounts/codex
              #     target: /home/shed/.codex
              #     readonly: false
              #   gh:
              #     source: ~/.shed/mounts/gh
              #     target: /home/shed/.config/gh
              #     readonly: false

              # Environment file (KEY=value per line, injected into VMs)
              # env_file: ~/.shed/env

              # Extensions provide credential brokering from host to VM.
              # Requires shed-host-agent to be installed and running:
              #   brew install shed-host-agent
              #   brew services start shed-host-agent
              # extensions:
              #   enabled:
              #     - ssh-agent
              #     - aws-credentials
              #     - docker-credentials

              firecracker:
                kernel_path: /var/lib/shed/firecracker/images/vmlinux
                base_rootfs: ghcr.io/charliek/shed-fc-base:v0.3.5
                images:
                  base: ghcr.io/charliek/shed-fc-base:v0.3.5
                instance_dir: /var/lib/shed/firecracker/instances
                socket_dir: /var/run/shed/firecracker
                default_cpus: 2
                default_memory_mb: 4096
                default_disk_gb: 20
                vsock_base_cid: 100
                console_port: 1024
                notify_port: 1026
                start_timeout: 90s
                stop_timeout: 10s
                bridge_name: shed-br0
                bridge_cidr: 172.30.0.1/24
                tap_prefix: shed-tap
            YAML
          end
        end
      end
    end
  end

  def post_install
    if OS.mac?
      require "tempfile"
      tmp = Tempfile.new(["shed-entitlements", ".plist"])
      tmp.write <<~XML
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>com.apple.security.virtualization</key>
          <true/>
        </dict>
        </plist>
      XML
      tmp.flush
      system "codesign", "--force", "--sign", "-",
             "--entitlements", tmp.path,
             "#{bin}/shed-server"
      tmp.close!
    end
  end

  def caveats
    <<~EOS
      The shed-server config has been installed to:
        #{HOMEBREW_PREFIX}/etc/shed/server.yaml

      Edit the config to enable credential mounts and extensions,
      then start shed-server as a background service:
        brew services start shed

      To enable extensions (SSH agent forwarding, AWS credentials,
      Docker credentials), also install the host agent:
        brew install shed-host-agent

      Logs: #{var}/log/shed-server.log

      Note: shed-server requires Docker for VM image management.
    EOS
  end

  service do
    run [opt_bin/"shed-server", "serve", "--config", etc/"shed/server.yaml"]
    keep_alive true
    log_path var/"log/shed-server.log"
    error_log_path var/"log/shed-server.log"
    environment_variables PATH: "/usr/local/bin:#{std_service_path_env}"
  end

  test do
    system bin/"shed", "version"
  end
end
