# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShedMachineRc < Formula
  desc "RC session helper for native machines (claude remote-control), sibling of shed-ext-rc"
  homepage "https://github.com/charliek/shed-extensions"
  version "0.4.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charliek/shed-extensions/releases/download/v0.4.9/shed-machine-rc_darwin_amd64.tar.gz"
      sha256 "08838ba318281e66fdc1e43f4202dba10ac848c5d5b41a1e09544ec0584dbf5b"

      define_method(:install) do
        bin.install "shed-machine-rc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charliek/shed-extensions/releases/download/v0.4.9/shed-machine-rc_darwin_arm64.tar.gz"
      sha256 "b7fb478268adc23dca5009d40b0245eea348c15e1146570dd6c59a19817a7f7f"

      define_method(:install) do
        bin.install "shed-machine-rc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/shed-extensions/releases/download/v0.4.9/shed-machine-rc_linux_amd64.tar.gz"
      sha256 "21227b1054752519aa4ddc576730310cbf3b44708c94927acbc00afc8c5c0f93"
      define_method(:install) do
        bin.install "shed-machine-rc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/shed-extensions/releases/download/v0.4.9/shed-machine-rc_linux_arm64.tar.gz"
      sha256 "b351050ba74dad5ebd16c31fcd3817b0cdf6d5825c8e137682c28bb580593663"
      define_method(:install) do
        bin.install "shed-machine-rc"
      end
    end
  end

  test do
    system bin/"shed-machine-rc", "version"
  end
end
