# typed: false
# frozen_string_literal: true

# Generated by charliek/strix's release workflow (scripts/release/strix.rb.tmpl
# rendered by .github/workflows/release.yml). DO NOT EDIT.
class Strix < Formula
  desc "A focused, polished TUI for staging changes and viewing diffs"
  homepage "https://github.com/charliek/strix"
  version "0.0.4"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charliek/strix/releases/download/v0.0.4/strix_darwin_amd64.tar.gz"
      sha256 "5319b2fc28ef782d947e167c9b5ec31ba7a475e08b63578ae9d18313f3583da6"

      define_method(:install) do
        bin.install "strix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charliek/strix/releases/download/v0.0.4/strix_darwin_arm64.tar.gz"
      sha256 "91340796eb3468b32d2444ace585f4a45552454e5157e4a0978678cc8e3519a7"

      define_method(:install) do
        bin.install "strix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/strix/releases/download/v0.0.4/strix_linux_amd64.tar.gz"
      sha256 "c03086049fc9f2fb48914e2fc1d1202af6d35ea37d899b1961ed97fe596cb84c"

      define_method(:install) do
        bin.install "strix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/strix/releases/download/v0.0.4/strix_linux_arm64.tar.gz"
      sha256 "fc36d96f4953352b4daaaa3f6de94975fbae66d8b9df004c6c0d4d47811c117a"

      define_method(:install) do
        bin.install "strix"
      end
    end
  end

  test do
    system bin/"strix", "--version"
  end
end
