# typed: false
# frozen_string_literal: true

# Generated by charliek/strix's release workflow (scripts/release/strix.rb.tmpl
# rendered by .github/workflows/release.yml). DO NOT EDIT.
class Strix < Formula
  desc "A focused, polished TUI for staging changes and viewing diffs"
  homepage "https://github.com/charliek/strix"
  version "0.0.1"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charliek/strix/releases/download/v0.0.1/strix_darwin_amd64.tar.gz"
      sha256 "48c75a717d12f4dd03a1d8f5ca0d1bfc3ebb1051823b6e6de80a49533995ec28"

      define_method(:install) do
        bin.install "strix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charliek/strix/releases/download/v0.0.1/strix_darwin_arm64.tar.gz"
      sha256 "32468bd1bef0d30e4f570495b912a3c86a99f95b8b9a0205ff3281644a82c16a"

      define_method(:install) do
        bin.install "strix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/strix/releases/download/v0.0.1/strix_linux_amd64.tar.gz"
      sha256 "557818b92621166f307fef6b137eaf400643d64ddcfc8aa02c6285bef8256dbe"

      define_method(:install) do
        bin.install "strix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliek/strix/releases/download/v0.0.1/strix_linux_arm64.tar.gz"
      sha256 "5208577c981d281950b24aded2c4acd2943ba98728e00a25253cfb3d928f4144"

      define_method(:install) do
        bin.install "strix"
      end
    end
  end

  test do
    system bin/"strix", "--version"
  end
end
